
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: pizzaorders.alpha.rudeboy.io
spec:
  group: alpha.rudeboy.io
  names:
    kind: PizzaOrder
    listKind: PizzaOrderList
    plural: pizzaorders
    shortNames:
    - pz
    singular: pizzaorder
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: order price
      jsonPath: .status.price
      name: price
      type: string
    - description: prep start time
      jsonPath: .status.tracker.prep
      name: prep
      type: string
    - description: bake start time
      jsonPath: .status.tracker.bake
      name: bake
      type: string
    - description: quality check start time
      jsonPath: .status.tracker.qualityCheck
      name: quality check
      type: string
    - description: delivered time
      jsonPath: .status.tracker.delivered
      name: delivered
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: PizzaOrder is the Schema for the pizzaorders API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PizzaOrderSpec defines the desired state of PizzaOrder
            properties:
              address:
                properties:
                  city:
                    type: string
                  phone:
                    pattern: '[2-9]\d{9}$'
                    type: string
                  postalCode:
                    type: string
                  region:
                    maxLength: 2
                    type: string
                  street:
                    type: string
                required:
                - city
                - phone
                - postalCode
                - region
                - street
                type: object
              customer:
                properties:
                  email:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                required:
                - email
                - firstName
                - lastName
                type: object
              paymentSecret:
                description: LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              pizzas:
                items:
                  properties:
                    size:
                      enum:
                      - small
                      - medium
                      - large
                      type: string
                    toppings:
                      items:
                        type: string
                      type: array
                  required:
                  - size
                  - toppings
                  type: object
                minItems: 1
                type: array
              placeOrder:
                type: boolean
            required:
            - address
            - customer
            - pizzas
            - placeOrder
            type: object
          status:
            description: PizzaOrderStatus defines the observed state of PizzaOrder
            properties:
              delivered:
                type: boolean
              orderID:
                type: string
              placed:
                type: boolean
              price:
                type: string
              store:
                properties:
                  address:
                    type: string
                  id:
                    type: string
                type: object
              tracker:
                properties:
                  bake:
                    type: string
                  delivered:
                    type: string
                  outForDelivery:
                    type: string
                  prep:
                    type: string
                  qualityCheck:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
